### ISSUE TITLE
Add libqt5multimedia5-plugins to installable packages for xUbuntu 20.04

### ISSUE THREAD

**Issue by TotalCaesar659** [olegantonyan/mpz#100]
When installing mpz on Lubuntu 20.04.1 from [PPA](https://software.opensuse.org//download.html?project=home%3Aoleg_antonyan&package=mpz), it installs only **libqt5multimedia5** and **mpz** packages, so mpz doesn't play sound. Installing **libqt5multimedia5-plugins** package manually solves it.

**Comment by olegantonyan** [comment]
Fixed in build 1.0.1.1 (https://github.com/olegantonyan/mpz/commit/d46f7657dda6a412250d48d805c4056f14d8d0a5)
Thanks!
