### ISSUE TITLE
Reduce padding in track window

### ISSUE THREAD

**Issue by vexillia** [olegantonyan/mpz#112]
This is an enhancement request.

The padding used in the track listing is too big.  The end result is that thee is a lot of space and too few tracks  listed for a given window size.  The directory and playlist paddings are great.

Could you either reduce it or make it user controlled?

Thanks.
![Screenshot_2020-10-20_08-47-33](https://user-images.githubusercontent.com/23417456/96556484-f04c2c00-12b0-11eb-88fc-71a48484412f.png)

**Comment by olegantonyan** [comment]
This happens because of small window width. Some tracks' names don't fit into cells. Year and duration got shortened, but not album/title. Making them shorter with "..." omission will probably look even worse.
There's a plan (#55) to make playlist columns configurable. This will allow you to select columns and theirs width.

**Comment by vexillia** [comment]
I appreciate this but the padding is too big even when the text hasn't wrapped (which is a good solution btw).  I have tested this full screen with no wrapping and it's too large.

![Screenshot_2020-10-20_09-09-36](https://user-images.githubusercontent.com/23417456/96558740-07404d80-12b4-11eb-8aaf-220458a0fffb.png)

**Comment by olegantonyan** [comment]
Which distro, desktop environment and screen resolution?

**Comment by vexillia** [comment]
xUbuntu 20.04, xcfe, 1920x1080

**Comment by vexillia** [comment]
Looking at this again I think the issue is this:  The line height is fixed and set assuming the text will wrap.  When it isn't it looks over padded.

Can the line height be set so it increases only if the text is wrapped and is otherwise tightly padded?

**Comment by olegantonyan** [comment]
> The line height is fixed and set assuming the text will wrap.
It shouldn't be the case. Look at screenshots https://olegantonyan.github.io/mpz/
Maybe a bug, I'll check it on your distro

**Comment by olegantonyan** [comment]
Fixed in 1.0.6

For some reason the default QTableRow's height in Xfce is substantially bigger than minimal. I've set it explicitly to minimal regardless of distro/DE settings

**Comment by vexillia** [comment]
Thanks.  Look great now.
