### ISSUE TITLE
Missing GStreamer plugins

### ISSUE THREAD

**Issue by roundoutandabout** [olegantonyan/mpz#119]
I'm getting such errors in the log:
```
Warning: "No decoder available for type 'audio/x-flac'."
Error: "Your GStreamer installation is missing a plug-in."
```
Could you please tell what plugins am I missing?

KDE neon 5.20 User Edition

**Comment by olegantonyan** [comment]
Looks like it is "good" plugins https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good/html/gst-plugins-good-plugins-plugin-flac.html

**Comment by roundoutandabout** [comment]
Yes, installing `gstreamer1.0-plugins-good` fixed the issue.
Thanks!
