### ISSUE TITLE
Ability to build with system libs

### ISSUE THREAD

**Issue by Vascom** [olegantonyan/mpz#126]
Please add ability to build with system libs at least **taglib** and **yaml-cpp**.

**Comment by olegantonyan** [comment]
This will eventually happen when I figure out how to use ffmpeg or libvlc or gstreamer directly instead of QtMultimedia.
Atm I'm not even sure if I want to keep taglib or switch to something else.

**Comment by olegantonyan** [comment]
It's now possible https://github.com/olegantonyan/mpz#from-sources= via `DEFINES+=USE_SYSTEM_TAGLIB` and/or `DEFINES+=USE_SYSTEM_YAMLCPP` qmake arguments
(tested on openSUSE and Arch)
