### ISSUE TITLE
 play dsf files

### ISSUE THREAD

**Issue by borisorlov21** [olegantonyan/mpz#160]
Tell me how to play dsf files, I can't understand whether it plays this format or not. But the sound quality is good.

**Comment by olegantonyan** [comment]
Formats' support depends on codecs installed on your OS. If there's codec then it should "just work"

**Comment by borisorlov21** [comment]
как установить кодек я новичек в линуксе расскажите пожалуйста плеер играет отлично басс мягкий хочу им пользоваться

**Comment by olegantonyan** [comment]
Как установлен плеер? Из AUR? https://aur.archlinux.org/packages/mpz или https://aur.archlinux.org/packages/mpz-qt5 ?

**Comment by borisorlov21** [comment]
первый вариант

**Comment by olegantonyan** [comment]
Можете дать пример файла который не воспроизводится?

**Comment by borisorlov21** [comment]
файлы от 300 до  500 мегабайт  в расширении дсф deadbeef востпоизводит но звук у него жесткий

**Comment by olegantonyan** [comment]
Так в чём проблема?

**Comment by borisorlov21** [comment]
нажимаю воспроизведение кнопка не нажимается воспр нет ладно буду слушать флак

**Comment by olegantonyan** [comment]
Пример файла который не воспроизводится покажите (сам файл целиком)

**Comment by borisorlov21** [comment]
https://mega.nz/file/75p0ABCL#0tCU9mjg8fQgC878cKUmD9vCFP-WqqlZos_ejN3lJ-k

**Comment by borisorlov21** [comment]
![Screenshot_20240906_105409](https://github.com/user-attachments/assets/ce851d3d-6b8a-4a1b-9f50-05767d093c0c)
это линукс эндевор на ноутбуке научился устанавливать из рупозитория арч здесь дсф работает

**Comment by borisorlov21** [comment]
подскажите пожалуйста как на монжаро устанавивать с репозитория арч приложения или на монжаро надо что то дополнительно устанавливать и напишите пожалуйста команды какие нужны

**Comment by borisorlov21** [comment]
чтото я делаю не так  в монжаро не работает

**Comment by olegantonyan** [comment]
`sudo pacman -S package_name`

**Comment by borisorlov21** [comment]
уж не знаю что тут к чему  я в арч 0 но в монжаро плеер заиграл дсф только вот при такой установке 
git clone https://github.com/olegantonyan/mpz.git
cd mpz
mkdir build
cd build
qmake-qt5 CONFIG+=release ..
make -j4
sudo make install

в эндевор установил с репозитория арч 
спасибо за плеер
